name: Push to GCR GitHub Action

on:
  push:
    branches:
      - main  # Replace with your desired branch name

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Set up Google Cloud SDK
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 -d > /tmp/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
       env:
       PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      
      - name: Build and Push Docker Image to GCR
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/$PROJECT_ID/backend:latest -f userdata/Dockerfile .
          docker push gcr.io/$PROJECT_ID/backend:latest
